-- PRAJAPATI ADVERTISING ERP PHASE 5 PROFESSIONAL WEB SCHEMA
create extension if not exists "uuid-ossp";
create table if not exists erp_roles(id uuid primary key default uuid_generate_v4(), role_name text unique not null, can_view_finance boolean default false, can_view_client_amount boolean default false, can_approve_expense boolean default false, created_at timestamptz default now());
insert into erp_roles(role_name,can_view_finance,can_view_client_amount,can_approve_expense) values
('admin',true,true,true),('accountant',true,true,true),('sales',false,true,false),('operation',false,false,true),('printing',false,false,false),('stitching',false,false,false),('execution',false,false,false),('client',false,true,false) on conflict(role_name) do nothing;
create table if not exists erp_projects(id uuid primary key default uuid_generate_v4(), project_code text unique not null, client_name text not null, city text, service text, quantity int default 0, client_amount numeric(12,2) default 0, status text default 'order_created', deadline date, created_by text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists erp_project_stages(id uuid primary key default uuid_generate_v4(), project_id uuid references erp_projects(id) on delete cascade, stage text not null, assigned_to text, status text default 'pending', progress int default 0 check(progress>=0 and progress<=100), started_at timestamptz, completed_at timestamptz, remarks text, created_at timestamptz default now());
create table if not exists erp_expenses(id uuid primary key default uuid_generate_v4(), project_id uuid references erp_projects(id) on delete cascade, work_type text, team_name text, location text, category text not null, amount numeric(12,2) not null default 0, bill_url text, submitted_by text, approved_by text, approval_status text default 'pending', payment_status text default 'unpaid', paid_by text, paid_at timestamptz, created_at timestamptz default now());
create table if not exists erp_client_progress(id uuid primary key default uuid_generate_v4(), project_id uuid references erp_projects(id) on delete cascade, public_token text unique default encode(gen_random_bytes(12),'hex'), printing_progress int default 0, stitching_progress int default 0, execution_progress int default 0, report_url text, invoice_url text, client_note text, updated_at timestamptz default now());
create table if not exists erp_activity_logs(id uuid primary key default uuid_generate_v4(), project_id uuid references erp_projects(id) on delete cascade, actor_name text, actor_role text, action text not null, details jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists erp_invoices(id uuid primary key default uuid_generate_v4(), project_id uuid references erp_projects(id) on delete cascade, invoice_no text unique, taxable_amount numeric(12,2) default 0, gst_amount numeric(12,2) default 0, total_amount numeric(12,2) default 0, payment_status text default 'pending', pdf_url text, created_at timestamptz default now());
create or replace view erp_project_profitability as select p.id,p.project_code,p.client_name,p.client_amount,coalesce(sum(e.amount),0) as total_expense,(p.client_amount-coalesce(sum(e.amount),0)) as net_profit,case when p.client_amount>0 then round(((p.client_amount-coalesce(sum(e.amount),0))/p.client_amount)*100,2) else 0 end as margin_percent from erp_projects p left join erp_expenses e on e.project_id=p.id and e.approval_status in ('approved','paid') group by p.id,p.project_code,p.client_name,p.client_amount;
create index if not exists idx_erp_projects_status on erp_projects(status);create index if not exists idx_erp_expenses_project on erp_expenses(project_id);create index if not exists idx_erp_stages_project on erp_project_stages(project_id);
